format = """
[ ](bg:#9A348E)\
$os\
$username\
[@](bg:#9A348E fg:#DEDEDE)\
$hostname\
[](fg:#9A348E bg:#C2817D)\
$git_branch\
$git_status\
[](fg:#C2817D bg:#666B98)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#666B98 bg:#33657A)\
[ ](fg:#06969A bg:#33657A)\
$time\
[ ](fg:#33657A)
[ ](bg:#BA3941)\
$directory\
[](fg:#BA3941)
[ 󰈺 ](fg:#DEDEDE bg:#555555)\
[ ](fg:#555555)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#DEDEDE bg:#9A348E"
style_root = "fg:#DEDEDE bg:#9A348E"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
format = '[$hostname ]($style)'
style = "fg:#DEDEDE bg:#9A348E"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = "[$symbol]($style)"
style = "fg:#DEDEDE bg:#9A348E"
disabled = false

[directory]
style = "fg:#DEDEDE bg:#BA3941"
format = "[$path ]($style)"
truncation_length = 0
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#DEDEDE bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#DEDEDE bg:#C2817D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#DEDEDE bg:#C2817D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#DEDEDE g:#666B98"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ](fg:#CE1717 bg:#666B98)[$version ](fg:#DEDEDE bg:#666B98)'

[scala]
symbol = " "
style = "fg:#DEDEDE bg:#666B98"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#DEDEDE bg:#33657A"
format = '[ $time ]($style)'
